from __future__ import annotations


def default_dense_params() -> dict:
    return {
        "op_type": "dense",
        "equation": None,
        "kernel_shape": None,
        "input_shape": None,
        "output_shape": None,
        "kernel_values": None,
        "kernel_float_values": None,
        "qkernel_values": None,
        "bias_values": None,
        "qbias_values": None,
        "uses_qkernel": False,
        "input_quantizer": None,
        "kernel_quantizer": None,
        "bias_quantizer": None,
        "output_quantizer": None,
        "input_qint": None,
        "input_kif": None,
        "kernel_qint": None,
        "kernel_kif": None,
        "bias_qint": None,
        "bias_kif": None,
        "output_qint": None,
        "output_kif": None,
        "has_bias": False,
        "has_bn": False,
        "bn_folded_into_qkernel": False,
        "activation": None,
        "kernel_sparsity": None,
        "kernel_nonzero_count": None,
        "kernel_zero_count": None,
        "kernel_unique_values": None,
        "kernel_unique_count": None,
        "kernel_min": None,
        "kernel_max": None,
        "kernel_dtype": None,
        "in_bw": None,
        "kq_bw": None,
        "out_bw": None,
        "sparsity": None,
    }

